<?php 
/*
 * @copyright   Copyright ( c) 2014 www.magebuzz.com
 */
?>
<?php 
	$helper = Mage::helper('ajaxlogin');
	$isIncludeJs = $helper->includeJs();
?>
<?php if($helper->isEnabled()): ?>
	<?php if($isIncludeJs):?>
		<script src="<?php echo $this->getJsUrl('magebuzz/ajaxlogin/jquery-1.10.1.min.js');?>" type="text/javascript"></script>
	<?php endif; ?>
	<script src="<?php echo $this->getJsUrl('magebuzz/ajaxlogin/fancybox/jquery.fancybox.js');?>" type="text/javascript"></script>
<?php endif; ?>